### ISSUE TITLE
"There was a problem running VMAF"

### ISSUE THREAD

**Issue by seacat17** [Withenex/vmaf-gui#11]
Tried to compare two H.264 MKV files. Got this error.
![изображение](https://user-images.githubusercontent.com/105108853/193369645-833d3617-9762-4182-924d-9a44d4f60198.png)

**Comment by ThatNerdUKnow** [comment]
This can happen if the video files are different lengths, framerates or *maybe* resolutions. Could you share this information for both files?

**Comment by ThatNerdUKnow** [comment]
Also, does this occur if you choose a different vmaf model?

**Comment by seacat17** [comment]
> Also, does this occur if you choose a different vmaf model?

Yes, it occurs. 

> This can happen if the video files are different lengths, framerates or _maybe_ resolutions. Could you share this information for both files?

I can't do this _right now_ but be sure - both of them were 1080p and had exactly same frametate and length. The only things that were different are codecs and bitrates I was trying to compare. This happened to all files I tried to test, and it didn't happened to original VMAF which I had to try.

**Comment by ThatNerdUKnow** [comment]
@seacat17 Okay, I should be able to hammer out a release soon that should give us more insight to what's happening to either ffmpeg or vmaf under the hood. While it won't fix the problem itself, it should let us know what's going on and allow us to investigate further

**Comment by ThatNerdUKnow** [comment]
@seacat17 I just put out release 2.1.2 which should provide us more insight into what's going wrong under the hood. Kindly download the latest release, then please share the errors that show up here

**Comment by ThatNerdUKnow** [comment]
I just put out release 2.1.3, That should resolve this issue
