### ISSUE TITLE
"System.FormatException: The input string format is incorrect"

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [Withenex/vmaf-gui#13]
Using 2.1.3, I'm getting this error. I've linked the screenshot of it (parts of it are in French)
![image](https://github.com/ThatNerdUKnow/vmaf-gui/assets/44057002/a360f1f7-0ce8-4a10-9732-5b2d246762c8)
Both files are in .mp4, the source is in H264 and the compressed one is in AV1

**Comment by toutrob** [comment]
I have exactly the same error with 2 .mkv files in H264. My Windows is also in French, maybe that's something to do with that?

**Comment by ThatNerdUKnow** [comment]
The problem seems to be with the part where I'm reading the xml file generated by vmaf to show the results. Could you share a copy of an xml file generated by vmaf-gui? If I remember correctly they should be getting generated in the root directory of the executable

**Comment by toutrob** [comment]
Yes sure.
[https://drive.google.com/file/d/1lg5cvpzxJwNuusC6OvWlzHWIfLydE7QZ/view?usp=sharing](https://drive.google.com/file/d/1lg5cvpzxJwNuusC6OvWlzHWIfLydE7QZ/view?usp=sharing)

**Comment by ThatNerdUKnow** [comment]
One more question, what's the absolute path to that xml file on your drive?

**Comment by toutrob** [comment]
C:\Users\robin\Downloads\vmaf-gui.2.1.3\Release

**Comment by ThatNerdUKnow** [comment]
Strange, I wouldn't think that path would cause a format exception. I'll need to investigate what can cause `Xdocument.Load` to throw a formatexception

**Comment by ThatNerdUKnow** [comment]
If I force vmaf-gui to skip all processing and load the XML @toutrob provided, it seems to load just fine. That could possibly rule out the formatting of the XML document. I do also wonder if this is a character encoding thing, perhaps the behavior of XDocument.load depends on the locale of the system?

**Comment by ThatNerdUKnow** [comment]
Okay, I think I've got it. Apparently the french locale uses commas instead of periods to represent decimal points. It looks like I should be able to override the locale that XDocument is using to load the xml file, so I'm going to give that a try.

**Comment by ThatNerdUKnow** [comment]
@toutrob , can you please try using this release?
https://github.com/ThatNerdUKnow/vmaf-gui/releases/tag/2.1.4

**Comment by toutrob** [comment]
It works perfectly for me, thank you for your work!
