### ISSUE TITLE
HUGE temporary files left behind

### ISSUE THREAD

**Issue by rcliftonharvey** [Withenex/vmaf-gui#15]
The application seems to do the VMAF analysis in two steps: decompress the video(s?) first into temporary files, then do the VMAF analysis over the decompressed video(s).

When I do a VMAF run, a "temp" folder is created inside the application path, this is where the decompressed files are stored. After the VMAF run is done, and/or the application is exited, the temporary files in this "temp" folder remain there, they are NOT deleted.

This would not be of much concern, if the files weren't INSANELY huge. For reference: a 4:22 minute 1080p/24fps reference video that was encoded from 100 MB into a 75 MB distorted 1080p/24fps video left behind two 25 GB files (=50 GB in total) in the "temp" folder.

I haven't tested it, but this would mean "temporary" files of nearly 500 GB could be generated (and left behind) for a simple VMAF run over a 45 minute 1080p/24fps video clip.

If this is really the case, then the app should make sure...
A) that this space is actually available on the drive where the application is located, or
B) that the user can select a different location (e.g. different drive) for those temporary files, and/or
C) that "temporary" files are actually temporary and get deleted after a VMAF analysis run completes.

Alternatively, FFMPEG offers the ability to decompress "on the fly", to my understanding without any 500 GB intermediate temporary files. If I do CLI VMAF runs, I call FFMPEG like this:

`ffmpeg.exe -threads 0 -i V:\Distorted.mp4 -i V:\Reference.mov -threads 0 -lavfi libvmaf="model='path=C\\\:/ffmpeg/vmaf/vmaf_v0.6.1.json':log_fmt=xml:log_path=V\\\:/Distorted.vmaf.xml" -f null -`

This assumes that...
- the bin location for ffmpeg.exe is set in `PATH` 
- reference and distorted videos are on drive `V:`
- the VMAF model files are installed in `C:\ffmpeg\vmaf\*.json`
- the output log file is supposed to go next to the distorted file on `V:`

Like this, I can have FFMPEG chug through a video file entirely and do VMAF analysis without generating (and leaving behind) any temporary files, especially not 500 GB worth of them.

Maybe that's an option for this application as well?

**Comment by rcliftonharvey** [comment]
Sorry, only just now saw that the new RUST version is supposed to fix this. Apologies for the disturbance, keep up the good work! :)

**Comment by ThatNerdUKnow** [comment]
@rcliftonharvey I have an experimental CLI available if you'd like to give it a try. UI work has been at a standstill given the state of rust native UI at the moment as well as personal matters
