### ISSUE TITLE
Possible to add an output to a plot where the vmaf values are plotted on a graph or a table?

### ISSUE THREAD

**Issue by rohitghali** [Withenex/vmaf-gui#6]
Something like this.

Episode | Length  | Size  | Q:Avg | Q:75% | Q:25% | Q:01%
--------+---------+-------+-------+-------+-------+------
S02E01  |   55:48 |  340M | 94.30 | 95.53 | 92.46 | 83.12
S02E02  |   54:09 |  323M | 94.20 | 95.41 | 92.17 | 81.80
S02E03  |   55:10 |  288M | 94.03 | 95.21 | 92.21 | 82.81
S02E04  |   54:43 |  293M | 93.68 | 95.04 | 91.71 | 82.71
S02E05  |   56:57 |  301M | 94.02 | 95.13 | 92.45 | 83.68
S02E06  |   58:08 |  323M | 94.19 | 95.40 | 92.48 | 83.94
S02E07  |   55:19 |  297M | 94.04 | 95.42 | 92.29 | 84.77
S02E08  |   56:03 |  332M | 93.97 | 95.49 | 91.79 | 81.31

**Comment by ThatNerdUKnow** [comment]
Actually it should be possible to plot vmaf scores to a graph, even on a per frame basis. Were asking vmaf to output to a xml file. All we'd have to do is to parse that data and then plot it. Are you also suggesting that we track subsequent runs as well?

**Comment by rohitghali** [comment]
Subsequent runs? Didn't understand.

**Comment by ThatNerdUKnow** [comment]
In your comment it looked like what you were proposing was to be able to compare multiple files (multiple runs of vmaf)

**Comment by rohitghali** [comment]
Im actually looking for an option for the vmaf values in the XML file to be plotted on a graph. So that it is easy to judge instead of digging into the XML. Current implementation works fine. But after the XML is generated, if vmaf values of individual frames is plotted against the vmaf value. It'd be a more intuitive output.

**Comment by rohitghali** [comment]
![images](https://user-images.githubusercontent.com/42379398/165336401-68dd9343-52df-47b3-a88f-811a812ded1e.png)
Something like this.

**Comment by ThatNerdUKnow** [comment]
I see what you mean. And we want to compare each frame to the average score?

**Comment by rohitghali** [comment]
It is already comparing each frame right? In the XML.log it shows a vmaf of every frame. Im talking about making a graph or some kind of presentable way of outputting it instead of XML.

**Comment by rohitghali** [comment]
I don't know how hard it is to implement, but it'd be great.

**Comment by ThatNerdUKnow** [comment]
Like I said, I'd have to use an xml reader to parse out those individual values and then make a pop up form or something to display it. Should be pretty doable

**Comment by rohitghali** [comment]
And also, it is unpacking the whole video, both source and compressed ones which takes up huge amount of disk space. NMKODER is somehow giving a vmaf value of two files without that. Much more efficient. Check it out once. I don't know how they're doing it, but to calculate vmaf, it is not taking up so much space.

**Comment by rohitghali** [comment]
And how do I select different models available?

**Comment by ThatNerdUKnow** [comment]
I'd need to add a form control for that. In previous versions of vmaf gui this was possible but for the 2.0 release I was too lazy to fix it

**Comment by rohitghali** [comment]
Oh. I hope you'll add it. Thanks.

**Comment by ThatNerdUKnow** [comment]
I was able to extract the correct data from the xml log but I've never used the chart form control before and I could use some help on how to bind the data to the control

**Comment by ThatNerdUKnow** [comment]
```c#
public void showResults(string path)
        {
            var doc = XDocument.Load(path);


            var frames = from frame in doc.Root.Descendants("frame")
                         select frame;

            var pooled_metrics = from metric in doc.Root.Descendants("pooled_metrics")
                                 where metric.Attribute("name").Value == "vmaf"
                                 select metric;

           

            DataPointCollection data = null;
            foreach(var frame in frames)
            {
                double frameNum = double.Parse(frame.Attribute("frameNum").Value);
                double vmafScore = double.Parse(frame.Attribute("vmaf").Value);
                data.AddXY(frameNum, vmafScore);
                Console.WriteLine(frame);
            }
            
            //TODO Bind vmaf data to results form control
            
        }
```

**Comment by rohitghali** [comment]
I'm really sorry man. No idea about C#. Hope someone helps.

**Comment by ThatNerdUKnow** [comment]
Current progress: https://github.com/ThatNerdUKnow/vmaf-gui/commit/95dc5e0cb9975f169dc577471dd7d86481c9624d
Still working on getting the mean vmaf score from the xml file but LINQ is giving me a hard time

**Comment by ThatNerdUKnow** [comment]
Finished feature branch here: https://github.com/ThatNerdUKnow/vmaf-gui/pull/8

**Comment by ThatNerdUKnow** [comment]
https://github.com/ThatNerdUKnow/vmaf-gui/releases/tag/2.1.0
Release for this feature
