### ISSUE TITLE
Selectable OS Threads

### ISSUE THREAD

**Issue by ThatNerdUKnow** [Withenex/vmaf-gui#7]
Currently the vmaf invocation will always use 4 threads. Setting threads to 0 uses only a single thread. We'd have to detect the number of is threads and inject it into the vmaf invocation

**Comment by luigi311** [comment]
perhaps just prompt the user for max threads to use in general for everything and set that as the vmaf_thread count. Vmaf doesnt infinitely scale so i would rather it not use all my threads on a 5950x.

**Comment by ThatNerdUKnow** [comment]
Good point, I found the default of four threads was pretty good but user-selectable cpu threads are a better idea
